<a href="https://colab.research.google.com/github/olibou145/training/blob/main/00_tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
print(tf.__version__)

2.6.0


In [13]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [14]:
scalar.ndim

0

In [10]:
vector=tf.constant([10,10])
vector


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [9]:
vector.ndim

1

In [7]:
matrix = tf.constant([[10,7],[7,10]])
matrix


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [8]:
matrix.ndim

2

In [20]:
matrix = tf.constant([[7.,10.,12.],[5.2,11.2,4.],[3.14,6.28,6.]], dtype=tf.float16)

matrix

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[ 7.  , 10.  , 12.  ],
       [ 5.2 , 11.2 ,  4.  ],
       [ 3.14,  6.28,  6.  ]], dtype=float16)>

In [21]:
matrix.ndim

2

In [23]:
tensor = tf.constant([  
                      [[1,2,3],[4,5,6]],
                      [[7,8,9],[10,11,12]],
                      [[13,14,15],[16,17,18]],
                      ])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [24]:
tensor.ndim

3