<a href="https://colab.research.google.com/github/olibou145/training/blob/main/00_tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercise from section 14 :  tf.constant

First use of tensorflow in python.


First step **import tensorflow** using tf.constant

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.6.0


**A scalar is a tensor of dim 0**

In [ ]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
scalar.ndim

0

**A vector is a tensor of dim 1 ( 1 dimension array )**


In [ ]:
vector=tf.constant([10,10])
vector


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

**A matrix is a tensor of dim 2 ( 2 dimension array )**


In [ ]:
matrix = tf.constant([[10,7],[7,10]])
matrix


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

specify the type of each element (ex: matrix of float16)

In [ ]:
matrix = tf.constant([[7.,10.,12.],[5.2,11.2,4.],[3.14,6.28,6.]], dtype=tf.float16)

matrix

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[ 7.  , 10.  , 12.  ],
       [ 5.2 , 11.2 ,  4.  ],
       [ 3.14,  6.28,  6.  ]], dtype=float16)>

In [ ]:
matrix.ndim

2

**A tensor is a n-dimension object (i.e. an array of matrix)**

In [ ]:
tensor = tf.constant([  
                      [[1,2,3],[4,5,6]],
                      [[7,8,9],[10,11,12]],
                      [[13,14,15],[16,17,18]],
                      ])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

# Exercice from section 15: tf.variable

In [1]:
import tensorflow as tf
